##
## File to use with superBake 0.x
##
## @copyright     Copyright 2012, Manuel Tancoigne (http://experimentslabs.com)
## @author        Manuel Tancoigne <m.tancoigne@gmail.com>
## @link          http://experimentslabs.com Experiments Labs
## @package       ELCMS.superBake.Configuration
## @license       GPL v3 (http://www.gnu.org/licenses/gpl.html)
## @version       0.3
##
##-----------------------------------------------------------------------
##
## Configuration file for ExperimentsLabs
## -------------------------
##      Acl plugin configuration.
##
##
##-----------------------------------------------------------------------
---
plugins:
  ## --------------------------------------------------------------------------
  ##  Acl manager
  ## ----------------------------
  ##  Here for menu items (for now)
  ## --------------------------------------------------------------------------
  ##
  Acl:
    haveBootstrap: true

    options:
      icon: shield
      useAjax: true

    path: Plugin

    generate: true

    ##
    ## Generated files
    files:
      bootstrap:
        targetPath: Config::bootstrap.php
        template: Acl::bootstrap

    ##
    ## Required files
    required:
      ## The AclRouter lib
      Acl-router:
        type: file
        source: libs::Acl::AclRouter.php
        target: Lib::AclRouter.php

    parts:
      ##
      ## Actions management (Acos)
      Actions:
        haveModel: false
        controller:
          actions:
            ## All default actions removed
            public:
              index:
                blackListed: true
              view:
                blackListed: true
            user:

              index:
                blackListed: true
              view:
                blackListed: true
              add:
                blackListed: true
              edit:
                blackListed: true
              delete:
                blackListed: true
            admin:
              ## All default actions removed (except index)
              view:
                blackListed: true
              edit:
                blackListed: true
              add:
                blackListed: true
              delete:
                blackListed: true
              ## Actions from controller:
              ## We "trick" the system: the template used for index contains all the actions.
              ## All the other actions points to an empty template.
              index:
                template: Acl::actions
                haveView: false
              build_acl:
                template: empty_action
                haveView: false
              empty_acos:
                template: empty_action
                haveView: false
              prune_acos:
                template: empty_action
                haveView: false
              synchronize:
                template: empty_action
                haveView: false

      ##
      ## Permission management (Aros)
      Permissions:
        haveModel: false
        controller:
          actions:
            ## All default actions removed
            public:
              index:
                blackListed: true
              view:
                blackListed: true
            user:
              index:
                blackListed: true
              view:
                blackListed: true
              add:
                blackListed: true
              edit:
                blackListed: true
              delete:
                blackListed: true
            ## All default actions removed (except index)
            admin:
              view:
                blackListed: true
              edit:
                blackListed: true
              add:
                blackListed: true
              delete:
                blackListed: true
              ## Actions from controller:
              ## We "trick" the system: the template used for index contains all the actions.
              ## All the other actions points to an empty template.
              index:
                template: Acl::permissions
              ajax_role_permissions:
                template: empty_action
              check:
                template: empty_action
              clear_user_specific_permissions:
                template: empty_action
              deny_all_controllers:
                template: empty_action
              deny_role_permission:
                template: empty_action
              deny_user_permission:
                template: empty_action
              empty_permissions:
                template: empty_action
              get_role_controller_permission:
                template: empty_action
              get_user_controller_permission:
                template: empty_action
              grant_all_controllers:
                template: empty_action
              grant_role_permission:
                template: empty_action
              grant_user_permission:
                template: empty_action
              role_permissions:
                template: empty_action
              update_user_role:
                template: empty_action
              user_permissions:
                template: empty_action
              users:
                template: empty_action
