##
## File to use with superBake 0.x
##
## @copyright     Copyright 2012, Manuel Tancoigne (http://experimentslabs.com)
## @author        Manuel Tancoigne <m.tancoigne@gmail.com>
## @link          http://experimentslabs.com Experiments Labs
## @package       ELCMS.superBake.Templates.Elabs
## @license       GPL v3 (http://www.gnu.org/licenses/gpl.html)
## @version       0.3
##
##-----------------------------------------------------------------------
##
## Configuration file for ExperimentsLabs
## -------------------------
##     Blog plugin configuration.
##
##
##-----------------------------------------------------------------------
---
plugins:
  ## --------------------------------------------------------------------------
  ##  Blog plugin
  ## ----------------------------
  ##  Write stuff !
  ## --------------------------------------------------------------------------
  ##
  Blog:
    options:
      icon: book
    displayName: Articles
    generate: true
    parts:
      ## Posts
      Posts:
        controller:
          actions:
            public:
              view:
                options:
                  conditions:
                    Post.published: 1
                view:
                  options:
                    hiddenFields:
                      published
                      created
                      modified

              index:
                options:
                  defaultSortBy: publication_date
                  conditions:
                    Post.published: 1
                    Post.publication_date <=: %now%
                view:
                  template: index::article
                  options:
                    ## unsortable fields:
#                    unSortableFields:
#                      text
                    ## Title
                    titleField: title
                    ## Content
                    contentField: excerpt
                    ## Creation date
                    cDateField: publication_date
                    ## Modification date
                    #mDateField:
                    ## Category
                    catField: post_category_id
                    ## Licensefield
                    licenseField: license_id
                    ## Author:
                    authorField: user_id
                    # Have a Safe for Work field
                    sfwField: sfw
                    # Have an Anon field
                    anonField: anon
            user:
              index:
                options:
                  conditions:
                    user_id: %self%
                view:
                  options:
                    conditions:
                      user_id: %self%
                    hiddenFields:
                      text_fra
                      text_eng
                      excerpt_fra
                      excerpt_eng
                      created
                      user_id
              add:
                options:
                  conditions:
                    user_id: %self%
                  hiddenAssociations:
                    User
            admin:
              index:
                options:
                  defaultSortBy: publication_date
                view:
                  options:
                   hiddenFields:
                      text_fra
                      text_eng
                      excerpt_fra
                      excerpt_eng
                      created

        options:
          icon: book
          fieldNames:
            user_id: Author
      ## Post categories
      PostCategories:
        options:
          icon: list-ul
          fieldNames:
            user_id: Author
        controller:
          actions:
            public:
              view:
                options:
                  containConditions:
                    Post:
                      published: 1

